window.env = {
  "NVM_INC": "/Users/macbook/.nvm/versions/node/v14.15.1/include/node",
  "TERM_PROGRAM": "vscode",
  "NODE": "/Users/macbook/.nvm/versions/node/v14.15.1/bin/node",
  "NVM_CD_FLAGS": "",
  "ANDROID_HOME": "/Users/macbook/Library/Android/sdk",
  "INIT_CWD": "/Users/macbook/Projects/Sides/Web/mrandi96.github.io",
  "TERM": "xterm-256color",
  "SHELL": "/bin/bash",
  "TMPDIR": "/var/folders/yp/36vxwfhn3x768y3583743mw00000gn/T/",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "TERM_PROGRAM_VERSION": "1.63.0",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "COLOR": "1",
  "npm_config_noproxy": "",
  "NVM_DIR": "/Users/macbook/.nvm",
  "USER": "macbook",
  "COMMAND_MODE": "unix2003",
  "npm_config_globalconfig": "/Users/macbook/.nvm/versions/node/v14.15.1/etc/npmrc",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.ieBMEqQWB5/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F5:0:2",
  "BASH_SILENCE_DEPRECATION_WARNING": "1",
  "npm_execpath": "/Users/macbook/.nvm/versions/node/v14.15.1/lib/node_modules/npm/bin/npm-cli.js",
  "PATH": "/Users/macbook/Projects/Sides/Web/mrandi96.github.io/node_modules/.bin:/Users/macbook/Projects/Sides/Web/node_modules/.bin:/Users/macbook/Projects/Sides/node_modules/.bin:/Users/macbook/Projects/node_modules/.bin:/Users/macbook/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/Users/macbook/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Users/macbook/Projects/Sides/Web/mrandi96.github.io/node_modules/.bin:/Users/macbook/Projects/Sides/Web/node_modules/.bin:/Users/macbook/Projects/Sides/node_modules/.bin:/Users/macbook/Projects/node_modules/.bin:/Users/macbook/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/Users/macbook/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Users/macbook/.nvm/versions/node/v14.15.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/macbook/.nvm/versions/node/v14.15.1/bin:/Users/macbook/Library/Android/sdk/emulator:/Users/macbook/Library/Android/sdk/tools:/Users/macbook/Library/Android/sdk/tools/bin:/Users/macbook/Library/Android/sdk/platform-tools:/Users/macbook/gocode/bin:/Users/macbook/Library/Android/sdk/emulator:/Users/macbook/Library/Android/sdk/tools:/Users/macbook/Library/Android/sdk/tools/bin:/Users/macbook/Library/Android/sdk/platform-tools:/Users/macbook/gocode/bin",
  "_": "/Users/macbook/Projects/Sides/Web/mrandi96.github.io/node_modules/.bin/react-dotenv",
  "npm_package_json": "/Users/macbook/Projects/Sides/Web/mrandi96.github.io/package.json",
  "__CFBundleIdentifier": "com.microsoft.VSCode",
  "npm_config_init_module": "/Users/macbook/.npm-init.js",
  "npm_config_userconfig": "/Users/macbook/.npmrc",
  "PWD": "/Users/macbook/Projects/Sides/Web/mrandi96.github.io",
  "npm_command": "run-script",
  "EDITOR": "vi",
  "npm_lifecycle_event": "build",
  "LANG": "en_GB.UTF-8",
  "npm_package_name": "mrandi96.github.io",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "XPC_FLAGS": "0x0",
  "npm_config_node_gyp": "/Users/macbook/.nvm/versions/node/v14.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "XPC_SERVICE_NAME": "0",
  "npm_package_version": "0.1.0",
  "SHLVL": "4",
  "HOME": "/Users/macbook",
  "VSCODE_GIT_ASKPASS_MAIN": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "LOGNAME": "macbook",
  "npm_config_cache": "/Users/macbook/.npm",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/yp/36vxwfhn3x768y3583743mw00000gn/T/vscode-git-e827a2b217.sock",
  "NVM_BIN": "/Users/macbook/.nvm/versions/node/v14.15.1/bin",
  "GOPATH": "/Users/macbook/gocode",
  "PROMPT_COMMAND": "enter_directory",
  "npm_config_user_agent": "npm/7.20.3 node/v14.15.1 darwin x64 workspaces/false",
  "VSCODE_GIT_ASKPASS_NODE": "/Applications/Visual Studio Code.app/Contents/MacOS/Electron",
  "GIT_ASKPASS": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "COLORTERM": "truecolor",
  "npm_config_prefix": "/Users/macbook/.nvm/versions/node/v14.15.1",
  "npm_node_execpath": "/Users/macbook/.nvm/versions/node/v14.15.1/bin/node",
  "API_KEY": "AIzaSyDv2N6jMpgd3v4o7YZuW7qRWxabKi6n7yU",
  "AUTH_DOMAIN": "github-pages-ac16a.firebaseapp.com",
  "PROJECT_ID": "github-pages-ac16a",
  "STORAGE_BUCKET": "github-pages-ac16a.appspot.com",
  "MESSAGING_SENDER_ID": "784440320686",
  "APP_ID": "1=784440320686=web=9afcdd79c80d148548433f"
};